### ISSUE TITLE
Cannot Parse *.scss Files With Classnames of "filter" or "from"

### ISSUE THREAD

**Issue by pmaher** [vaadin/sass-compiler#12]
I have a simple .scss file with the following rule:
div .filter { color: red; }
Note the class name is "filter". When trying to parse this I get the following error:

Dec 09, 2015 12:45:43 AM com.vaadin.sass.internal.handler.SCSSErrorHandler log
SEVERE: encountered "filter". Was expecting one of: "-" "and" "or" "not" "#{" "through" "in" <IDENT> 
org.w3c.css.sac.CSSParseException: encountered "filter". Was expecting one of: "-" "and" "or" "not" "#{" "through" "in" <IDENT> 
    at com.vaadin.sass.internal.parser.Parser.reportError(Parser.java:419)
    at com.vaadin.sass.internal.parser.Parser.styleRule(Parser.java:2203)
    at com.vaadin.sass.internal.parser.Parser.topLevelDeclaration(Parser.java:591)
    at com.vaadin.sass.internal.parser.Parser.parserUnit(Parser.java:487)

A similar exception occurs with the following css rule using classname = "from"

div .from { color: red; }

**Comment by lipodido** [comment]
Hello,

Did anyone find a solution for this issue.

Regards

**Comment by sirbris** [comment]
I'm also still facing this issue... workaround like suggested here: https://github.com/vaadin/sass-compiler/issues/117

```
  $agentFilter: "drop-shadow(0px 3px 8px #ccc)";
  filter: #{$agentFilter};
  -webkit-filter: #{$agentFilter};
```

but it won't work like that if I want to replace the color #ccc with another scss-variable e.g.
